[connections.gsheets]
snd_url = "https://docs.google.com/spreadsheets/d/1WUZDXuJSYOgegrpFnKivzroItzUdI0D5yCC9HxPKE4Q/edit"
hp_url = "https://docs.google.com/spreadsheets/d/1n02f4wAPaPiOQQ0Q_efKeD3iageS13UVDxm253ApRss/edit"
ctrl_url = "https://docs.google.com/spreadsheets/d/1yDLBpgpv6l23rWWKtBHoy-LAmC75oFTsklUSJNPH9MQ/edit"
